language: node_js
node_js:
  - "14"
  - "12"
  - "10"
script:
  - npm test
  - npm run cover
after_success:
  - node test/bench
  - npm run coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
